version: 1.0.0
fonts:
  CJK:
    name: "ERDA CC-BY CJK"
    paths:
      - ".github/fonts/erda-ccby-cjk/true-type/erda-ccby-cjk.ttf"
    license: "Creative Commons Attribution 4.0 International (CC BY 4.0)"
    license_url: "https://creativecommons.org/licenses/by/4.0/"
    source_url: null

  EMOJI:
    name: "Twemoji Mozilla"
    paths: [] # System font
    license: "CC BY 4.0"
    license_url: "https://creativecommons.org/licenses/by/4.0/"
    source_url: "https://github.com/mozilla/twemoji-colr"

  MONO:
    name: "DejaVu Sans Mono"
    paths: [] # System font
    license: "SIL Open Font License 1.1"
    license_url: "https://scripts.sil.org/cms/scripts/page.php?item_id=OFL"
    source_url: "https://dejavu-fonts.github.io/"

  SANS:
    name: "DejaVu Sans"
    paths: [] # System font
    license: "SIL Open Font License 1.1"
    license_url: "https://scripts.sil.org/cms/scripts/page.php?item_id=OFL"
    source_url: "https://dejavu-fonts.github.io/"

  SERIF:
    name: "DejaVu Serif"
    paths: [] # System font
    license: "SIL Open Font License 1.1"
    license_url: "https://scripts.sil.org/cms/scripts/page.php?item_id=OFL"
    source_url: "https://dejavu-fonts.github.io/"
