name: Documentation QA

on:
  push:
    paths:
      - '**/*.md'
      - 'docs/confidential/QA/tools/docs/**'
      - 'docs/public/documents/**'
      - 'docs/confidential/project/**'
      - 'docs/confidential/QA/tools/reports/**'
      - 'docs/confidential/QA/tools/logs/**'
      - 'docs/confidential/QA/tools/tests/**'
  pull_request:
    paths:
      - '**/*.md'
      - 'docs/confidential/QA/tools/docs/**'
      - 'docs/public/documents/**'
      - 'docs/confidential/project/**'
      - 'docs/confidential/QA/tools/reports/**'
      - 'docs/confidential/QA/tools/logs/**'
      - 'docs/confidential/QA/tools/tests/**'

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run QA pipeline
        run: |
          PYTHONPATH=. pytest docs/confidential/QA/tools/tests/qa -q
